### ISSUE TITLE
could you please share some example training data and folders?

### ISSUE THREAD

**Issue by etworker** [debidatta/syndata-generation#1]
because it is not easy to reconstruct the same test environment.

If provide example environment will help to run code, thanks!

**Comment by debidatta** [comment]
Added expected directory structure in this [commit](https://github.com/debidatta/syndata-generation/commit/03006d2fbf417b6f15883fc2ab3336b2974ca56d). Also added expected output directory in this [commit](https://github.com/debidatta/syndata-generation/commit/29953441245d795fcbd079f70ca62e7e6ad0d759) . Hope this helps :)
