### ISSUE TITLE
create_mask function is not defined

### ISSUE THREAD

**Issue by surajbharadwaj** [debidatta/syndata-generation#10]

**Comment by debidatta** [comment]
Install poisson blending from here which has create_mask function https://github.com/yskmt/pb

**Comment by surajbharadwaj** [comment]
thank you very much. What about unbound local error?is it related to multithreading? can you give a solution for the other issue which i have opened?

**Comment by debidatta** [comment]
Replied on the original [issue](https://github.com/debidatta/syndata-generation/issues/9). Closing this one.
