### ISSUE TITLE
mask process

### ISSUE THREAD

**Issue by surajbharadwaj** [debidatta/syndata-generation#11]
Can you share the process of generating mask for images?
the code and steps in detail

it would be of great help

**Comment by chho-work** [comment]
Do you mean the masks like "NP123.pbm" in  demo_data_dir/robjects_dir/honey_bunches ?
I think you can reproduce them using:
https://github.com/debidatta/pixelobjectness-bp
as the authors mentioned in Pre-Requisite.
I already succeeded deploying dataset_generator.py in the demo data.  Now I am trying to reproduce the mask.

**Comment by surajbharadwaj** [comment]
I saw that. But can it be used for custom objects as well?

**Comment by chho-work** [comment]
I read this: "We propose an end-to-end learning framework for foreground object segmentation. Given a single novel image, our approach produces a pixel-level mask for all "object-like" regions---even for object categories never seen during training. "
It's in their project page: http://vision.cs.utexas.edu/projects/pixelobjectness/
So I think it should be valid for custom object as well.

**Comment by chho-work** [comment]
Someone asked similar question already.  You can find it in this closed thread:
https://github.com/debidatta/syndata-generation/issues/6#issuecomment-440712443

**Comment by surajbharadwaj** [comment]
Hey,
I finally obtained mask automatically.
Used white background and captured images, and adobe photoshop did all the job. You can batch automate the process to obtain mask in photoshop

**Comment by Anna666488** [comment]
**@chho-work ，hello，I see you have already succeeded deploying dataset_generator.py in the demo data. I have some difficulties in running code. When I was running the code,the rusults directories had nothing.I'm refused,Do you know why? Could you help me? Thanks! It's very urgent!!!**

**Comment by chho-work** [comment]
@Anna666488 Sorry, don't think I can be of help at this moment!  I moved to something else later on, not so sure if I can reproduce what I did at that time.  If I find my original work, I will get back to you!

**Comment by Anna666488** [comment]
If you can find,It's Great! I really need your help.Thank you very much.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "debidatta/syndata-generation"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月30日(星期二) 下午2:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [debidatta/syndata-generation] mask process (#11)





 
@Anna666488 Sorry, don't think I can be of help at this moment!  I moved to something else later on, not so sure if I can reproduce what I did at that time.  If I find my original work, I will get back to you!
