### ISSUE TITLE
what is the dataset Type?

### ISSUE THREAD

**Issue by ogamache** [debidatta/syndata-generation#16]
Hello!

I have been able to create a nice dataset thanks to your project. But I need to modify the annotation to have a COCO format. I tried a couple of algorithms that transfer VOC format to COCO, but the annotation from your algorithm doesn't seem to match perfectly the VOC standard.

So, I was wondering what is your annotation template and if you know how to modify it to obtain a COCO format?

Thank you!

**Comment by debidatta** [comment]
Hi Olivier, 

Thanks for trying this out. The script produces annotations in the output_dir. An example of the annotations is [here](https://github.com/debidatta/syndata-generation/blob/master/output_dir/annotations/1.xml). Once you parse the XML using an [XML parser](https://docs.python.org/3/library/xml.etree.elementtree.html), you can use it to extract <object> tags with <name> denoting the object class and <bndbox> containing coordinates of box. For each image you can get a list of object and bounding boxes which you can use to convert to COCO format. This [blog](https://blog.roboflow.com/how-to-convert-annotations-from-voc-xml-to-coco-json/) might be helpful in converting from one form to another.

**Comment by ogamache** [comment]
Hi, 

Thanks for your answer. I finally was able to modify your output format to coco by adding some missing headers to the XML annotation files.

**Comment by debidatta** [comment]
Great! If you have a PR for switching to COCO annotations, I'll be happy to merge it.
