### ISSUE TITLE
background images

### ISSUE THREAD

**Issue by kassellevi1** [debidatta/syndata-generation#17]
first, thank you for your contribution.

for reserch propose i want to restore your experment that you have done in your article.

i have an difficulty to find the background images dataset that you are using in order to pasted the objects on them.
in the article i saw that you use this [dataset:](http://rgbd-dataset.cs.washington.edu/dataset.html)  from this [paper](https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=5980382)
there is a lot of background images there and not 1548 like you wrote in the paper and also the look a little diffrent from the examples in the paper.
can you give me the link of the background image dataset ?
thanks

**Comment by debidatta** [comment]
Thanks for your interest in this work.

I used the background scenes from [here](https://rgbd-dataset.cs.washington.edu/dataset/rgbd-scenes/). Please let me know if this works for you.

**Comment by kassellevi1** [comment]
thats helps alot.
thanks
