### ISSUE TITLE
unable to reproduce results

### ISSUE THREAD

**Issue by cnut1648** [debidatta/syndata-generation#18]
Hi, thanks for your repo!

I would like to reproduce your results for Table1 last row (76.2). And here is what I did. I run your code with

```
python dataset_generator.py /path/to/BigBird /path/to/exp --selected --add_distractors
```
where `selected` is all 11 objects in the BigBird overlapping with UW Scene, 
![image](https://user-images.githubusercontent.com/37067883/148695069-e5b80fc3-c290-453a-bf38-af8e4051842d.png)
and neg_list is all others
![image](https://user-images.githubusercontent.com/37067883/148695078-6e8de89c-8431-4bf6-b1e0-46bdda7df0b0.png)
and in `defaults.py` the `BACKGROUND_DIR` is set to be the path to the 1548 images in the UW Scene (extracted from the `background.tar`)

I didn't change other settings in the `defaults.py` and use all different blendings (5 in total, `['gaussian','poisson', 'none', 'box', 'motion']`)

Is my setting correct? In the end I created 2632 annotation xml, and 2632 * 5 = 13160 images (with 5 blendings).

**Comment by cnut1648** [comment]
An update, so I have trained Detectron2 faster rcnn (pretrained on COCO), and the result are quite low
![image](https://user-images.githubusercontent.com/37067883/148708768-db624a0d-bf0a-47b6-912c-ea3cfbb58e39.png)

I think I kept the original parameters, and my config is below

```
class Trainer(DefaultTrainer):
    @classmethod
    def build_evaluator(cls, cfg, dataset_name):
        return COCOEvaluator("synthetic_train", output_dir=os.path.join(cfg.OUTPUT_DIR, "eval", dataset_name))

with open(cutpasted_dir / "label2id.json") as f:
        label2id = json.load(f)

from PIL import ImageFile, Image
ImageFile.LOAD_TRUNCATED_IMAGES = True

register_coco_instances("synthetic_train", metadata=label2id, json_file=str(cutpasted_dir / "COCO.json"), image_root=str(cutpasted_dir / "images"))
register_coco_instances("kitchen_test", metadata={}, json_file=str(data_dir / "Kitchen_fold1_COCO.json"), image_root="")
cfg = get_cfg()

cfg.merge_from_file(model_zoo.get_config_file("COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml"))
cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.5  # set threshold for this model
cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml")
cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 256
cfg.MODEL.ROI_HEADS.NUM_CLASSES = len(label2id)

cfg.DATASETS.TRAIN = ("synthetic_train",)
cfg.DATASETS.TEST = ("synthetic_train", )
cfg.DATALOADER.NUM_WORKERS = 10
cfg.TEST.EVAL_PERIOD = 5000

cfg.SEED = 42

cfg.SOLVER.IMS_PER_BATCH = 4
cfg.SOLVER.BASE_LR = 0.001
cfg.SOLVER.MAX_ITER = 25000
cfg.SOLVER.STEPS = (15000, )
cfg.SOLVER.WEIGHT_DECAY = 0.0005

os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
trainer = Trainer(cfg) 
trainer.resume_or_load(resume=False)
trainer.train()
```
what did I miss here? Thank you!

**Comment by cnut1648** [comment]
After several days I have been successfully reproduce the result! [Here is my attempt](https://github.com/cnut1648/syndata-generation3). The code is using python3 and contains FCN training code (use torchvision) and also object detection module (using detectron2). Thank you again for the authors' great work!

**Comment by zeldrinn** [comment]
@cnut1648 any chance you still have that code lying around? Getting a 404 :)
