### ISSUE TITLE
Error when running with defaults.

### ISSUE THREAD

**Issue by EthanReid** [debidatta/syndata-generation#3]
I'm having a little bit of trouble getting started. I'm running this project on Ubuntu 16.04 and I believe that I have all the required dependencies. When I try to run `python3 dataset_generator.py
` I am met with `File "dataset_generator.py", line 151
    print "%s not found. Using empty mask instead."%mask_file
                                                  ^
SyntaxError: Missing parentheses in call to 'print'
`

Any idea why. I am probably missing something really simple, but any help would be very much appreciated.

**Comment by debidatta** [comment]
The code in the repository was tested with Python 2 only. You need to call print as a function in Python 3 for this code to work. This fork https://github.com/yueweiyang/syndata-generation/blob/master/dataset_generator.py makes the required changes for the code to run with Python 3.

**Comment by EthanReid** [comment]
Thanks for that. I get a new error. 
` Traceback (most recent call last):
  File "dataset_generator.py", line 19, in <module>
    from pb import *
ImportError: No module named 'pb'
`
Do you by chance know whats going on here? I cant find a module named "pb" on google.

**Comment by debidatta** [comment]
pb refers to the Poisson blending library: https://github.com/yskmt/pb

**Comment by EthanReid** [comment]
I really appreciate the help with that, and sorry for the late reply. I fixed the issue with pb and made the necessary changes to run pyblur on python3. 

When I run `python3 dataset_generator.py root exp` i just get `Number of background images : 2`. 

I'm not sure why it is not generating the images. Am I missing something?

**Comment by EthanReid** [comment]
Thanks

**Comment by aeitel** [comment]
Hi,
I wanted to try your code and I have the same problem.
python dataset_generator.py ~/code/self/libs/syndata-generation/demo_data_dir ~/code/self/libs/syndata-generation/output_dir
Number of background images : 2
List of distractor files collected: []

While it does run, it does not write any images in output_dir/images
I tried a few print outs in function create_image_anno, but it seems the method is not entering that function, maybe its because of partial() or some problems with threading? 
Any suggestions?
Thanks

**Comment by aeitel** [comment]
Ok now I got it, with this command it runs.
python dataset_generator.py demo_data_dir/objects_dir output_dir

**Comment by miquel-espinosa** [comment]
> The code in the repository was tested with Python 2 only. You need to call print as a function in Python 3 for this code to work. This fork https://github.com/yueweiyang/syndata-generation/blob/master/dataset_generator.py makes the required changes for the code to run with Python 3.

It would be good to update the repo with the python3 version. 
Thanks.
