### ISSUE TITLE
"distractor_files" variable referenced before assignment

### ISSUE THREAD

**Issue by leetwito** [debidatta/syndata-generation#4]
line 432 raises error:
UnboundLocalError: local variable 'distractor_files' referenced before assignment
could be fixed easily, adding:
distractor_files = []
at the top of the function.

**Comment by debidatta** [comment]
Thanks for catching the mistake. Fixed in https://github.com/debidatta/syndata-generation/commit/9dbbbdba770ac0239795a26e8624bd8f93201218
