### ISSUE TITLE
How did you get the .pbm pictures?

### ISSUE THREAD

**Issue by baizhenmao95** [debidatta/syndata-generation#6]
Thanks for your work! But as a beginner, I have no idea how to generate the .pbm pictures in the objects_dir folder. I could just got a few by using Photoshop. But it's too slow.
So could you please tell me some better ways that you've used? Thank you very much!

**Comment by debidatta** [comment]
Hi,

There are ways to do foreground segmentation (finding pixels of the salient object in the image) using computer vision. If you are willing to click on object of interest you can use GrabCut (https://github.com/opencv/opencv/blob/master/samples/python/grabcut.py). If you want a more automated solution, you can take a look at [this](https://github.com/debidatta/pixelobjectness-bp). This is slightly dated. So, may be look at something a little more new: [this](https://github.com/AceCoooool/DSS-pytorch). I'll recommend using Bilinear pooling for cleaning masks. Don't worry about the .pbm extension. Once you get a binary mask as an image you can just store it as a pbm using OpenCV. Hope this helps.

**Comment by baizhenmao95** [comment]
Thank you very much! I'll have a try.
