### ISSUE TITLE
3D Rotation

### ISSUE THREAD

**Issue by gabrielibagon** [debidatta/syndata-generation#8]
In the paper, you mention rotating images in 3D, however, I only see 2D rotation implemented in this repo, in lines 305-306:

```
foreground_tmp = foreground.rotate(rot_degrees, expand=True)
mask_tmp = mask.rotate(rot_degrees, expand=True)
```

Is this correct that only 2D rotation is implemented here? Is 3D rotation achieved some other way?

**Comment by debidatta** [comment]
3D rotations were available because of the way the data was collected in the BigBIRD dataset by placing the object in front of multiple cameras at different elevation angles and rotating the turn-table. Unfortunately, this code doesn't add 3D rotations.
